# Generated by Django 5.2.3 on 2025-06-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_projectresource_utilization_percentage_resource_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='hourly_rate',
        ),
    ]
