# Generated by Django 5.2.3 on 2025-06-12 14:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_fake_migration_for_automation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OATReleaseCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SprintCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Weekly Automation Meeting', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='automation_framework_tech_stack',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='bugs_found_through_automation',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_of_last_automation_run',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='execution_time_of_smoke',
            field=models.CharField(blank=True, help_text='Hours and Minutes', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='oat_release_cycle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='pipeline_schedule',
            field=models.CharField(blank=True, choices=[('on_demand', 'On-Demand'), ('weekly', 'Weekly'), ('nightly', 'Nightly'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='readiness_for_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='regression_automation_status',
            field=models.CharField(blank=True, choices=[('hold', 'Hold'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='regression_coverage',
            field=models.IntegerField(blank=True, help_text='Percentage or count', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='smoke_automation_status',
            field=models.CharField(blank=True, choices=[('hold', 'Hold'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('na', 'N/A')], default='na', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='sprint_cycle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='status_of_last_automation_run',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_lead',
            field=models.ForeignKey(blank=True, db_column='team_lead_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_as_lead', to='dashboard.resource'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_automatable_smoke_test_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_automatable_test_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_automated_smoke_test_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_automated_test_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_number_of_available_test_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_number_of_business_test_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_number_of_functional_test_cases',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WeeklyProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smoke_automation_status', models.CharField(choices=[('hold', 'Hold'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('na', 'N/A')], default='na', max_length=20)),
                ('regression_automation_status', models.CharField(choices=[('hold', 'Hold'), ('completed', 'Completed'), ('in_progress', 'In Progress'), ('na', 'N/A')], default='na', max_length=20)),
                ('pipeline_schedule', models.CharField(choices=[('on_demand', 'On-Demand'), ('weekly', 'Weekly'), ('nightly', 'Nightly'), ('na', 'N/A')], default='na', max_length=20)),
                ('execution_time_hours', models.IntegerField(default=0)),
                ('execution_time_minutes', models.IntegerField(default=0)),
                ('total_available_test_cases', models.IntegerField(default=0)),
                ('bugs_found_through_automation', models.IntegerField(default=0)),
                ('regression_coverage', models.IntegerField(default=0)),
                ('total_automatable_test_cases', models.IntegerField(default=0)),
                ('total_automated_test_cases', models.IntegerField(default=0)),
                ('total_automated_smoke_test_cases', models.IntegerField(default=0)),
                ('last_automation_run_status', models.TextField(blank=True)),
                ('last_automation_run_date', models.DateField(blank=True, null=True)),
                ('automation_framework_tech_stack', models.TextField(blank=True)),
                ('functional_test_cases_count', models.IntegerField(default=0)),
                ('business_test_cases_count', models.IntegerField(default=0)),
                ('readiness_for_production', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.weeklymeeting')),
                ('oat_release_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.oatreleasecycle')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
                ('sprint_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sprintcycle')),
                ('team_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.resource')),
            ],
            options={
                'unique_together': {('meeting', 'project')},
            },
        ),
    ]
