# Generated by Django 5.2.3 on 2025-06-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_oatreleasecycle_sprintcycle_weeklymeeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter_number', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('name', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'quarter_number'],
                'unique_together': {('year', 'quarter_number')},
            },
        ),
        migrations.CreateModel(
            name='QuarterTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_description', models.TextField()),
                ('target_value', models.IntegerField(blank=True, help_text='Numeric target value if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_targets', to='dashboard.project')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='dashboard.quarter')),
            ],
        ),
        migrations.CreateModel(
            name='QuarterTargetResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Maximum 100%', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.quartertarget')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.resource')),
            ],
            options={
                'unique_together': {('quarter_target', 'resource')},
            },
        ),
        migrations.AddField(
            model_name='quartertarget',
            name='resources',
            field=models.ManyToManyField(through='dashboard.QuarterTargetResource', to='dashboard.resource'),
        ),
        migrations.AlterUniqueTogether(
            name='quartertarget',
            unique_together={('quarter', 'project')},
        ),
    ]
