# Generated by Django 5.2.3 on 2025-06-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_quarter_quartertarget_quartertargetresource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quarter',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quarter',
            name='completion_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quartertarget',
            name='achieved_value',
            field=models.IntegerField(blank=True, help_text='Actual achieved value', null=True),
        ),
        migrations.AddField(
            model_name='quartertarget',
            name='achievement_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quartertarget',
            name='achievement_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of target achieved', max_digits=5, null=True),
        ),
    ]
