# Generated by Django 5.2.3 on 2025-06-20 10:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_weeklyproductupdate_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='end_date',
            field=models.DateField(blank=True, help_text="End date of resource's involvement in the project", null=True),
        ),
        migrations.AddField(
            model_name='projectresource',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text="Start date of resource's involvement in the project"),
        ),
        migrations.CreateModel(
            name='ResourceLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick Leave'), ('personal', 'Personal Leave'), ('holiday', 'Holiday'), ('other', 'Other')], default='vacation', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='dashboard.resource')),
            ],
        ),
    ]
