# Generated by Django 5.2.3 on 2025-06-25 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_project_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the roadmap item')),
                ('end_date', models.DateField(help_text='End date of the roadmap item')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Date and time when the item was completed', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_roadmap_items', to='dashboard.resource')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_items', to='dashboard.project')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_items', to='dashboard.quarter')),
                ('quarter_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roadmap_items', to='dashboard.quartertarget')),
            ],
            options={
                'ordering': ['start_date', 'end_date', 'title'],
            },
        ),
    ]
