# Generated by Django 5.2.3 on 2025-06-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_roadmapitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(help_text='URL to the document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='dashboard.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
