# Generated by Django 5.2.3 on 2025-06-27 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_productdocumentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Production Issue Title', max_length=200)),
                ('gops_board_link', models.URLField(blank=True, help_text='GOPS Board Link')),
                ('product_board_link', models.URLField(blank=True, help_text='Product Board Link')),
                ('reported_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the issue was reported')),
                ('resolved_date', models.DateField(blank=True, help_text='Date when the issue was resolved', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('tested', 'Tested'), ('done', 'Done')], default='open', max_length=20)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('details', models.TextField(blank=True, help_text='Comments/Details about the issue')),
                ('test_case_added', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_bugs', to='dashboard.project')),
            ],
            options={
                'ordering': ['-reported_date', 'status', '-severity'],
            },
        ),
    ]
