# Generated by Django 5.2.3 on 2025-07-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_departmentdocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='readiness_for_production',
            new_name='in_development',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.AddField(
            model_name='project',
            name='in_production',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weeklymeeting',
            name='title',
            field=models.CharField(default='Automation Updates', max_length=200),
        ),
        migrations.AlterField(
            model_name='weeklyproductmeeting',
            name='title',
            field=models.CharField(default='Manual Updates', max_length=200),
        ),
    ]
