# Generated by Django 5.2.3 on 2025-07-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_deletedrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordsPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text='Password for accessing the Records section', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Records Password',
                'verbose_name_plural': 'Records Password',
            },
        ),
    ]
