# Generated by Django 5.0 on 2025-07-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_remove_quartertarget_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyproductupdate',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the product update'),
        ),
    ]
