# Generated by Django 5.0 on 2025-07-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_remove_weeklyproductupdate_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyproductupdate',
            name='product_notes',
            field=models.TextField(blank=True, help_text='Product notes and additional information'),
        ),
    ]
