# Generated by Django 5.0 on 2025-08-29 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_resource_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year (e.g., 2023)')),
                ('feedback', models.TextField(help_text='Monthly feedback for the resource')),
                ('status', models.CharField(choices=[('due', 'Feedback Due'), ('submitted', 'Submitted')], default='due', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_feedbacks', to='dashboard.resource')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_monthly_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Feedback',
                'verbose_name_plural': 'Monthly Feedbacks',
                'ordering': ['-year', '-month', 'resource'],
                'unique_together': {('resource', 'month', 'year')},
            },
        ),
    ]
