# Generated by Django 5.0 on 2025-08-29 10:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_sop_sopstatushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBackupResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_resources', to='dashboard.project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_for_projects', to='dashboard.resource')),
            ],
            options={
                'verbose_name': 'Product Backup Resource',
                'verbose_name_plural': 'Product Backup Resources',
                'unique_together': {('project', 'resource')},
            },
        ),
    ]
