# Generated by Django 5.0 on 2025-09-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_productbackupresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRunner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Automation Runner', max_length=200)),
                ('link', models.URLField(help_text='URL link to the runner board')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Automation Runner',
                'verbose_name_plural': 'Automation Runners',
                'ordering': ['name'],
            },
        ),
    ]
