# Generated by Django 5.0 on 2025-09-25 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_automationrunner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationSprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineering_manager_name', models.CharField(max_length=200)),
                ('sprint_length', models.CharField(choices=[('1_week', '1 week'), ('2_weeks', '2 weeks'), ('3_weeks', '3 weeks')], max_length=10)),
                ('total_dev_resources', models.IntegerField()),
                ('sprint_type', models.CharField(choices=[('6th_sprint', '6th Sprint'), ('20_allocation', '20% Allocation')], max_length=20)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('complete', 'Complete'), ('on_hold', 'On Hold'), ('to_do', 'To Do')], default='to_do', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('risks', models.TextField(blank=True)),
                ('dev_training_status', models.CharField(choices=[('completed', 'Completed'), ('in_progress', 'In Progress'), ('to_do', 'To Do')], default='to_do', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_sprint_days', models.IntegerField(default=0)),
                ('total_planned_working_hours', models.IntegerField(default=0)),
                ('blocked_hours', models.IntegerField(default=0)),
                ('total_planned_test_cases', models.IntegerField(default=0)),
                ('total_test_cases_automated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_sprints', to='dashboard.project')),
                ('qa_point_of_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_sprints', to='dashboard.resource')),
            ],
            options={
                'verbose_name': 'Automation Sprint',
                'verbose_name_plural': 'Automation Sprints',
                'ordering': ['-start_date', 'product__name'],
            },
        ),
    ]
