# Generated by Django 5.2.3 on 2025-06-12 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='utilization_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum 100%', max_digits=5),
        ),
        migrations.AddField(
            model_name='resource',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members_as_lead', to='dashboard.resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members_as_manager', to='dashboard.resource'),
        ),
        migrations.AddField(
            model_name='resource',
            name='skill',
            field=models.CharField(choices=[('automation', 'Automation'), ('manual', 'Manual'), ('both', 'Both')], default='manual', max_length=20),
        ),
    ]
