# Generated by Django 5.2.3 on 2025-06-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_resource_hourly_rate'),
    ]

    operations = [
        # This is a fake migration that doesn't actually change the database schema
        # It's just to mark the migration as applied in Django's migration history
        # The fields were already added to the database in a previous operation
    ]