# Generated by Django 5.2.3 on 2025-06-19 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_quarter_completed_quarter_completion_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProductMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='Weekly Product Meeting', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyProductUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='General notes about the product')),
                ('problems', models.TextField(blank=True, help_text='Problems identified during the meeting')),
                ('expected_solution', models.TextField(blank=True, help_text='Expected solution for the identified problems')),
                ('solution_timeline', models.CharField(choices=[('immediate', 'Immediate (1-2 days)'), ('short', 'Short-term (1 week)'), ('medium', 'Medium-term (2-4 weeks)'), ('long', 'Long-term (1+ months)')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.weeklyproductmeeting')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project')),
            ],
            options={
                'unique_together': {('meeting', 'project')},
            },
        ),
    ]
