# Generated by Django 5.2.3 on 2025-06-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_weeklyproductmeeting_weeklyproductupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyproductupdate',
            name='notes',
        ),
        migrations.AddField(
            model_name='weeklyproductupdate',
            name='latest_project_updates',
            field=models.TextField(blank=True, help_text='Latest updates about the product'),
        ),
        migrations.AlterField(
            model_name='weeklyproductupdate',
            name='expected_solution',
            field=models.TextField(blank=True, help_text='[Legacy] Expected solution for the identified problems'),
        ),
        migrations.AlterField(
            model_name='weeklyproductupdate',
            name='problems',
            field=models.TextField(blank=True, help_text='[Legacy] Problems identified during the meeting'),
        ),
        migrations.AlterField(
            model_name='weeklyproductupdate',
            name='solution_timeline',
            field=models.CharField(choices=[('immediate', 'Immediate (1-2 days)'), ('short', 'Short-term (1 week)'), ('medium', 'Medium-term (2-4 weeks)'), ('long', 'Long-term (1+ months)')], default='medium', help_text='[Legacy] Timeline for the solution', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField(help_text='Problem identified during the meeting')),
                ('expected_solutions', models.TextField(blank=True, help_text='Expected solutions for the identified problem')),
                ('solution_timeline', models.CharField(choices=[('immediate', 'Immediate (1-2 days)'), ('short', 'Short-term (1 week)'), ('medium', 'Medium-term (2-4 weeks)'), ('long', 'Long-term (1+ months)')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_problems', to='dashboard.weeklyproductupdate')),
            ],
        ),
    ]
