# Generated by Django 5.2.3 on 2025-06-23 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='budget',
        ),
    ]
