# Generated by Django 5.2.3 on 2025-06-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_roadmapitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmapitem',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
    ]
