# Generated by Django 5.2.3 on 2025-06-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_roadmapitem_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoadmapItem',
        ),
    ]
