# Generated by Django 5.2.3 on 2025-07-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='smoke_coverage',
            field=models.IntegerField(blank=True, help_text='Percentage of smoke test cases automated', null=True),
        ),
    ]
