# Generated by Django 5.2.3 on 2025-07-01 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_project_smoke_coverage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='The model class name of the deleted record', max_length=100)),
                ('record_id', models.IntegerField(help_text='The primary key of the deleted record')),
                ('data', models.TextField(help_text='JSON serialized data of the deleted record')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deleted Record',
                'verbose_name_plural': 'Deleted Records',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
