# Generated by Django 5.2.3 on 2025-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectresource',
            name='eta',
            field=models.DateField(blank=True, help_text='Estimated Time of Arrival/Completion', null=True),
        ),
    ]
