# Generated by Django 5.2.3 on 2025-07-07 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_projectresource_eta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the KPI', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the KPI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='dashboard.resource')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['resource', 'name'],
                'unique_together': {('resource', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KPIRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year (e.g., 2023)')),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Below Expectations'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Outstanding')], help_text='Rating from 1 to 5')),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks for this KPI rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='dashboard.kpi')),
            ],
            options={
                'verbose_name': 'KPI Rating',
                'verbose_name_plural': 'KPI Ratings',
                'ordering': ['-year', '-month', 'kpi'],
                'unique_together': {('kpi', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='KPIRatingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(help_text='Month (1-12)')),
                ('year', models.IntegerField(help_text='Year (e.g., 2023)')),
                ('overall_remarks', models.TextField(help_text='Mandatory overall remarks for this submission')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_submissions', to='dashboard.resource')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Rating Submission',
                'verbose_name_plural': 'KPI Rating Submissions',
                'ordering': ['-year', '-month', 'resource'],
                'unique_together': {('resource', 'month', 'year')},
            },
        ),
    ]
