# Generated by Django 5.0 on 2025-07-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_kpi_kpirating_kpiratingsubmission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quartertarget',
            unique_together=set(),
        ),
    ]
