# Generated by Django 5.0 on 2025-07-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_weeklyproductupdate_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyproductupdate',
            name='notes',
        ),
    ]
