# Generated by Django 5.0 on 2025-08-28 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_add_weeklyproductupdate_product_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOnOneFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(help_text='Feedback notes for the resource')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_on_one_feedbacks', to='dashboard.resource')),
            ],
            options={
                'verbose_name': '1:1 Feedback',
                'verbose_name_plural': '1:1 Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
