# Generated by Django 5.0 on 2025-08-29 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_monthlyfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the SOP', max_length=200)),
                ('link', models.URLField(help_text='URL link to the SOP document')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('review_done', 'Review Done'), ('rollout_in_progress', 'Rollout in Progress'), ('rollout_done', 'Rollout Done'), ('active', 'Active'), ('inactive', 'Inactive')], default='in_progress', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SOP',
                'verbose_name_plural': 'SOPs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SOPStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('review_done', 'Review Done'), ('rollout_in_progress', 'Rollout in Progress'), ('rollout_done', 'Rollout Done'), ('active', 'Active'), ('inactive', 'Inactive')], max_length=30)),
                ('new_status', models.CharField(choices=[('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('review_done', 'Review Done'), ('rollout_in_progress', 'Rollout in Progress'), ('rollout_done', 'Rollout Done'), ('active', 'Active'), ('inactive', 'Inactive')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='dashboard.sop')),
            ],
            options={
                'verbose_name': 'SOP Status History',
                'verbose_name_plural': 'SOP Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
    ]
